### ISSUE TITLE
Undefined property: stdClass::$bibtex

### ISSUE THREAD

**Issue by rhukster** [OleVik/grav-plugin-biblatex#1]
I just installed the plugin and got this error:

![crikey there was an error 2016-08-25 12-47-43](https://cloud.githubusercontent.com/assets/1084697/17981761/3efb264e-6ac2-11e6-81f4-b01057cf97d1.png)

**Comment by OleVik** [comment]
That is odd, what environment are you testing it with? From the error it has to do with the path-detection, which may need an additional condition for checking the specific page for `bibtex` before running forward.

I created and tested it on Grav v1.1.3, but the back-end library demonstrably fails quickly on slightly improper Bibtex-files without good reason. A better back-end library really is necessary for a better implementation, I've just yet to find a parser that delivers the goods.

Bibtex might also be inherently outdated compared with any modern format, JSON definitely would be better but I haven't dug into whether most or any Bibliography-software supports it as output.

**Comment by OleVik** [comment]
Just pushed a release with fixed plugin-detection, it would fail on pages with `bibtex` not set.

**Comment by rhukster** [comment]
That did it 👍
